config/routes.rb
ConferenceApp::Application.routes.draw do

  resources :feedback_votes


  get "roomslots/add_talk"
  get "roomslots/remove_talk"
  resources :talk_comments
  resources :roomslots
  resources :rooms
  resources :timeslots

  resources :workshop_participant

  #MyProfile
  get "my_profile/dinner_registration" => "my_profile#dinner_registration"
  get "my_profile/receipt" => "my_profile#receipt"
  resources :my_profile, :only => "index"

  #order stuff
  get "orders/new_user"
  post "orders/add_user"
  get "orders/show"
  resources :orders, :only => [:index, :show, :destroy]

  resources :sponsors

  get "administration/registrations"
  get "administration/send_mail"
  get "administration/statistics"
  get "administration/caches"
  post "administration/clear_caches"

  # program stuff
  get "program" => "program#index"
  get "program/program"

  #nametags
  get "/nametags" => "nametags#index"
  get "/nametags/:id" => "nametags#show"

  #Info sites
  get "info/about"
  get "info/tema"
  get "info/til_lyntalere"
  get "info/spre_ordet"
  get "info/direkte_mail"
  get "info/sponsor"
  get "info/index"
  get "info/policy"
  get "info/godbiter"
  get "info/gruppepaamelding"
  get "info/sponsor/request"
  get "info/david", to: redirect('/info/keynote')
  get "info/keynote"
  get "info/sosialt"
  get "info/arsmote"
  get "info/smidig_offentlig"
  post "info/sponsor"

  #twitter stuff
  get "twitter/smidig_feed"

  resources :talk_categories

  resources :talk_types

  post '/talks/:id/vote' => 'talks#vote', :as => 'vote'
  post '/talks/:id/status' => 'talks#status', :as => 'status'

  get "talks/list"
  resources :talks

  resources :tickets

  resources :settings

  resources :payment_notifications

  # payment stuff
  get "payments/paypal_completed"
  get "payments/manual_completed"
  get "payments/new_paypal"
  get "payments/new_manual"
  post "payments/create_manual"
  put "payments/update_manual"
  get "payments/complete"
  get "payments/manual"
  get "payments/finish"
  put "payments/invoice_sent"
  resources :payments

  # user stuff
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords" }
  get "users/make_admin"
  match "users/complete/:id" => "users#complete"
  get "users/speaker"
  resources :users
  get "users/delete/:id" => "users#delete"

  resources :tipped_users, :only => :create

  root :to => "my_profile#index"
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  attr_accessible :title, :description, :accepted_license, :talk_type, :talk_type_id, :talk_category, :talk_category_id, :users, :presentation, :as => [ :default, :admin ]
  attr_accessible :status, :user, :new_user, :user_ids, :registrations_open_at, :as => :admin
  attr_accessor :new_user

  acts_as_votable

  STATUS_OPTIONS = %w(approved_and_confirmed approved rejected pending)

  DEFAULT_MAX_WS_PARTICIPANTS = 20

  belongs_to :talk_type
  belongs_to :talk_category
  belongs_to :user
  has_and_belongs_to_many :users

  has_many :talk_comments
  
  belongs_to :roomslot

  has_many :workshop_participants
  has_many :feedback_votes

  has_attached_file :presentation, PAPERCLIP_CONFIG
  validates_attachment_size :presentation, :less_than => 50.megabytes

  validates :status, :inclusion => {:in => STATUS_OPTIONS}, :allow_nil => true

  validates_presence_of :title, :description, :talk_type, :talk_category

  validates_acceptance_of :accepted_license

  after_save    :expire_talk_all_cache
  after_destroy :expire_talk_all_cache

  def self.all_cached
    Rails.cache.fetch('Talk.all') { order('id desc').all }
  end

  def self.approved_cached
    Rails.cache.fetch('Talk.approved') { where(:status => 'approved_and_confirmed').all }
  end

  def self.talk_type_count_cached
    Rails.cache.fetch('Talk.talk_type_count') { talk_type_count }
  end

  def self.talk_type_count
    talk_count = []
    talk_type_id_approved_count = where("status = 'approved_and_confirmed' or status = 'approved'").count(:group => :talk_type_id)

    count(:group => :talk_type).each do |talk_type, count|
      o =  {
        :name => talk_type.name,
        :total => count,
        :approved => talk_type_id_approved_count[talk_type.id] || 0
      }
      talk_count.push(o)
    end

    talk_count
  end

  def expire_talk_all_cache
    Rails.cache.delete('Talk.all')
    Rails.cache.delete('Talk.approved')
    Rails.cache.delete('Talk.talk_type_count')
  end

  def ws_participant?(user)
    workshop_participants.map{|wp| wp.user_id}.include?(user.id)
  end

  def ws_full?
    workshop_participant_ids.count >= max_participants
  end

  def ws_free_places
    max_participants - workshop_participant_ids.count
  end

  def max_participants
    roomslot.try(:room).try(:size) || DEFAULT_MAX_WS_PARTICIPANTS
  end

end

app/models/talk_type.rb
class TalkType < ActiveRecord::Base
  attr_accessible :duration, :name, :visible

  has_many :talks

  def workshop
    name.downcase.include? "workshop"
  end
end

app/controllers/talks_controller.rb
# encoding: UTF-8
class TalksController < ApplicationController

  no_authorization! :only => [:new, :show, :list]

  authorize_admin! :only => [:index, :vote, :destroy, :status]

  authorize_user! :only => :create

  helper_method :get_talk_types, :get_voters

  authorize! :only => [:edit, :update] do
    talk = Talk.find(params[:id])

    unless current_user.admin? || talk.user == current_user
      permission_denied('Du er ikke taleren som opprettet denne talk', my_profile_index_path)
    end
  end

  before_filter :redirect_to_create_user_if_not_logged_in, :only => :new

  # GET /talks
  # GET /talks.json
  def index
    @talk_type_count = Talk.talk_type_count_cached

    @talks = Talk.all_cached

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @talks }
      format.csv {
        @filename = "Smidig_foredrag_#{Date.today.to_formatted_s(:db)}.csv"
      }
    end
  end

  def list
    #@talks = Talk.order('id desc').all
    @talks = Talk.approved_cached

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @talks }
    end
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
    @talk = Talk.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @talk }
    end
  end

  # GET /talks/new
  # GET /talks/new.json
  def new
    @talk = Talk.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @talk }
    end
  end

  # GET /talks/1/edit
  def edit
    if current_user.admin
      @talk_types = TalkType.all
    else
      @talk_types = TalkType.find(:all, :conditions => {:visible => true})
    end

    @talk = Talk.find(params[:id])
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(params[:talk], :as => admin? ? :admin : :default)
    @talk.user = current_user

    respond_to do |format|
      if @talk.save()
        format.html { redirect_to my_profile_index_path, notice: 'Takk, ditt foredragsforslag er registrert.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /talks/1
  # PUT /talks/1.json
  def update
    @talk = Talk.find(params[:id])
    @new_user = User.find_by_email(params[:talk][:new_user])


    respond_to do |format|
      if @talk.update_attributes(params[:talk], :as => (admin? || @talk.user == current_user) ? :admin : :default)
        # Change to be set on e-mail request insted of directly from edit form
        if @new_user
          @talk.users << @new_user
          @talk.save
        end

        format.html { redirect_to :back, notice: "Talk was successfully updated." }
        format.json { head :no_content }
        format.js {
          render "update",
                 :locals => {
                     :id => params[:id],
                     :talk => @talk
                 }
        }
      else
        format.html { render action: "edit" }
        format.json { render json: @talk.errors, status: :unprocessable_entity, notice: 'Failed' }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    @talk = Talk.find(params[:id])
    @talk.destroy
    flash[:notice] = "Talk has been deleted."

    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
    end
  end

  # POST /talks/1/vote
  def vote
    @talk = Talk.find(params[:id])
    @talk.vote :voter => current_user, :vote => !current_user.voted_as_when_voted_for(@talk)
    flash[:notice] = "Vote registered."

    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
      format.js {
        render "update",
               :locals => {
                   :id => params[:id],
                   :talk => @talk
               }
      }
    end
  end

  # POST /talks/1/status
  def status
    @talk = Talk.find(params[:id])
    @status = params[:status]

    unless @status == @talk.status
      @talk.status = @status
      @talk.save

      if (@status == "approved_and_confirmed")
        SmidigMailer.talk_acceptance_confirmation(@talk).deliver

        # Confirm user as speaker if talk gets approved
        unless @talk.user.completed
          @talk.user.completed = true
          @talk.user.save
        end

      elsif (@status == "rejected")
        SmidigMailer.talk_refusation_confirmation(@talk).deliver
      end
    end

    respond_to do |format|
      format.html { redirect_to talks_url }
      format.json { head :no_content }
      format.js {
        render "update",
               :locals => {
                   :id => params[:id],
                   :talk => @talk
               }
      }
    end
  end

  private

  def get_talk_types
    if current_user.admin
      @talk_types = TalkType.all
    else
      @talk_types = TalkType.find(:all, :conditions => {:visible => true})
    end
    return @talk_types
  end

  def get_voters(talk)
    voters = "";
    total_length = talk.upvotes.length - 1
    talk.upvotes.each_with_index do |vote, index|
      if vote.voter
        voters = voters + " " + vote.voter.name
      else
        voters = voters + "?(#{vote.id})"
      end
      
      if index < total_length
        voters = voters + ","
      end

    end
    return voters
  end

  def redirect_to_create_user_if_not_logged_in
    if not current_user
      session[:return_to] = request.fullpath
      flash[:notice] = "Du må opprette en bruker før du kan registrere en lyntale eller workshop. " +
          "Etter utfylling av din brukerinformasjon vil du få anledning til å angi innhold i foredraget ditt. " +
          "Dersom du allerede har en bruker kan du logge inn via \"Min Profil\"."
      redirect_to new_user_registration_path(:ticket_name => "Speaker")
      return false
    end
  end

end

app/helpers/talks_helper.rb
module TalksHelper
  def suggesting_talk?
    params[:ticket_name] == 'Speaker'
  end

  def talk_suggestion_deadline
    Date.parse setting_for('talk-deadline-passed', '2000-01-01 00:00:00')
  end
end

app/views/talks/_comments.html.haml
.talk_comments
  %ul 
    - for comment in talk.talk_comments
      %li 
        %span.time #{comment.created_at.to_formatted_s(:short)},
        %span.username #{comment.user.name}
        %br
        %span.comment #{comment.content}

  %form.form-inline
    %input{:type=>"hidden", :name => "user_id", :value => "#{current_user.id}"}
    %input{:type=>"hidden", :name => "talk_id", :value => "#{talk.id}"}
    %input{:type=> "text", :name => "content", :placeholder => "Skriv en kommentar"}
    %button{:type => "submit", :class => "btn btn-success"} Lagre

app/views/talks/_details.html.haml
%header
  %h1
    =talk.title
  %em.author
    =link_to(talk.user.name, edit_user_path(talk.user))
    - for user in talk.users
      ,
      =link_to(user.name, edit_user_path(user))
%p
  =simple_format talk.description

- if talk.presentation.file?
  = link_to talk.presentation.original_filename, talk.presentation.url

%div.talk-actions
  %hr

  =link_to "Editer", edit_talk_path(talk), :class => 'btn btn-success'
  =link_to "Slett", talk, confirm: t("helpers.confirm.delete"), :method => :delete, :class => 'btn btn-danger'

  %label.pull-right
    Status
    %div.btn-group
      - Talk::STATUS_OPTIONS.each do |status|
        =link_to status_path(talk, "status" => status), {:class => (status == talk.status ? "btn btn-success" : "btn"), :method => :post, :action => :status, :confirm => t("helpers.confirm.talk_status_change"), :remote => true} do

          - if status == "approved_and_confirmed"
            %i.icon-ok
            %i.icon-thumbs-up
            =t("activerecord.attributes.talk.status.approved_and_confirmed")
          - elsif status == "approved"
            %i.icon-thumbs-up
            =t("activerecord.attributes.talk.status.approved")
          - elsif status == "rejected"
            %i.icon-thumbs-down
            =t("activerecord.attributes.talk.status.rejected")
          - else
            %i.icon-time
            =t("activerecord.attributes.talk.status.pending")

app/views/talks/_form.html.haml
= simple_form_for @talk, :html => {:multipart => true, :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :description, input_html: { :class => "span6", :rows => "10" }
  = f.association :talk_type, :collection => get_talk_types()
  = f.association :talk_category
  - if @talk.presentation.file?
    %div.control-group
      %label.control-label
        Nåvarende presentasjon
      %div.controls
        = link_to @talk.presentation.original_filename, @talk.presentation.url

  = f.input :presentation, :as => :file, :label => 'Presentation', :hint => '(Lastes opp senest 24 timer før konferansen)'
  - if current_user.admin?
    = f.input :status, :collection => Talk::STATUS_OPTIONS, :label => 'Status', label_method: lambda {|s| t("activerecord.attributes.talk.status." + s)}
    = f.input :registrations_open_at, :as => :string, :input_html => { :type => 'datetime-local', :value => @talk.registrations_open_at.try(:strftime, '%Y-%m-%dT%H:%M') }
  - if @talk.created_at? or current_user.admin?
    = f.input :new_user, :label => 'Legg til ekstra taler', :hint => '(e-post til registrert deltager)'
    = f.association :users, as: :check_boxes, collection: @talk.users, :label => 'Ekstra talere'
  - else
    = f.input :accepted_license, :as => :boolean, :inline_label => 'Jeg forstår at foredraget blir gjort tilgjengelig med en Creative Commons Navngivelse 3.0 Norge lisens.', :label => false

  .form-actions
    = f.button :submit, :class => 'btn-primary', :value => 'Send inn forslag!'

app/views/talks/_talk.html.haml
%tr{:id => "talk_#{talk.id}"}
  %td{"data-sort-value" => talk.title, "data-value" => talk.title}
    (#{talk.id}) #{talk.title}
  %td
    =talk.user.name
    (#{talk.user.company})
  %td.votes{"data-sort-value" => talk.upvotes.size}
    .input-append
      %input.vote-input{:type=>"text", :disabled => 'disabled', :value => talk.upvotes.size}
      -if !current_user.voted_as_when_voted_for talk
        =link_to vote_path(talk), {:action => :vote, :method => :post, :class => 'btn', :remote => true} do
          %i.icon-thumbs-up
      -else 
        =link_to vote_path(talk), {:action => :vote, :method => :post, :class => 'btn btn-success', :remote => true} do
          %i.icon-thumbs-down
    -if talk.upvotes.size > 0
      %button.btn.pull-right.bs-tooltip{:title => get_voters(talk)}
        %i.icon-user
  %td{"data-sort-value" => t("activerecord.attributes.talk.status." + talk.status)}
    =t("activerecord.attributes.talk.status." + talk.status)
  %td
    -if !talk.talk_type.blank?
      =talk.talk_type.name
  %td
    -if !talk.talk_category.blank?
      =talk.talk_category.name
  %td
    =talk.created_at.to_formatted_s(:short)
  %td
    %a.btn.btn-success.expand
      %i.icon-plus
%tr.tablesorter-childRow
  %td{"colspan" => 4, "class" => "talk-details"}
    =render :partial => "details", locals: {talk: talk}
  %td{"colspan" => 4}
    =render 'comments', :talk => talk

app/views/talks/_talk_view.html.haml
.row-fluid.talk
  .span10
    %header
      %h4 
        =link_to talk.title, talk_path(talk)
        
      %em Foreslått av:     
      = talk.user.name
      - for user in talk.users
        ,
        =user.name

      %br
      %span
        - if talk.talk_type
          %em Type: 
          #{talk.talk_type.name}

      %span
        - if talk.talk_category
          | 
          %em Kategori: 
          #{talk.talk_category.name}

      %span
        - if talk.status
          | 
          %em Status: 
          #{talk.status == "approved_and_confirmed" ? "Godkjent" : "Registrert"}       
     
      %h6 Beskrivelse:
      = simple_format talk.description
  .span2

app/views/talks/edit.html.haml
%h1 Endre foredrag

= render 'form'

app/views/talks/index.html.haml
%a.pull-right{:href => "#{talks_path}.csv", :class => "btn"}
  %i.icon-th
  Eksporter som CSV

%header.clearfix
  %h1
    Foredrag

  %p= link_to 'Foreslå nytt foredrag', new_talk_url

%dl.dl-horizontal
  - for c in @talk_type_count
    %dt
      #{c[:name]}
    %dd
      #{c[:total]} / #{c[:approved]}

%article.main  
  %table.table.tablesorter
    %thead
      %tr
        %th
          (Id) Tittel
        %th
          Taler (bedrift)
        %th.sorter-sortOnDataAttrib.filter-parsed
          Stemmer
        %th.sorter-sortOnDataAttrib.filter-select{"data-placeholder" => "Alle"}
          Status
        %th.filter-select{"data-placeholder" => "Alle"}
          Foredrags type
        %th.filter-select{"data-placeholder" => "Alle"}
          Kategori
        %th.filter-false
          Opprettet
        %th.filter-false.sorter-false
    %tbody
      - for talk in @talks
        = render :partial => "talk", :locals => { :talk => talk }

app/views/talks/list.html.haml
%h1 Godkjente bidrag til Smidig 2016

%p 
  På denne siden kan du se alle godkjente lyntaler, workshops og foredrag 
  som skal danne grunnlaget for innholdet til Smidig 2016. 

- for talk in @talks
  = render 'talk_view', :talk => talk
   

app/views/talks/new.html.haml
%h1 Foreslå foredrag
%p
  Ved å fylle ut dette skjemaet, vil foredraget ditt bli registrert blant forslagene til årets konferanse.
  Du kan på et hvert tidspunkt i fremtiden endre innholdet på foredraget ditt. Andre deltagere får nå
  se forslaget ditt så snart det er registrert og du godtar at foredraget ditt deles under en
  Creative Commons lisens. Blir din lyntale tatt med, belønnes du med fri inngang, ære og forevigelse
  på video. Har du betalt, vil du få refundert beløpet.

%p
  Du kan også lese våre  
  %a(href="/info/til_lyntalere") tips til lyntalere
  dersom du trenger litt hjelp for å komme i gang. 

%p 
  %strong Siste frist for å sende inn ditt forslag er #{l talk_suggestion_deadline, :format => '%-d. %B'}!!

%br

= render 'form'

app/views/talks/show.html.haml
= render 'talk_view', :talk => @talk

- if @talk.talk_type.workshop
  %h3 Påmelding til Workshop
  = render 'workshop_participant/participate', :talk => @talk
  
//%a(href="/talks/list") Tilbake til alle foredrag

%br 
%br
%a(href="/program") Til programmet

app/views/talks/update.js.erb
var $talk = $("#talk_<%=id%>")
	open = !$talk.find(".expand").hasClass("btn-success");

$talk.next().remove();
$talk.replaceWith("<%= escape_javascript(render :partial => talk)%>");

if(open) {
	$("#talk_<%=id%>").find(".expand").trigger("click");
}

$(".tablesorter").trigger("update");