config/routes.rb
ConferenceApp::Application.routes.draw do

  resources :feedback_votes


  get "roomslots/add_talk"
  get "roomslots/remove_talk"
  resources :talk_comments
  resources :roomslots
  resources :rooms
  resources :timeslots

  resources :workshop_participant

  #MyProfile
  get "my_profile/dinner_registration" => "my_profile#dinner_registration"
  get "my_profile/receipt" => "my_profile#receipt"
  resources :my_profile, :only => "index"

  #order stuff
  get "orders/new_user"
  post "orders/add_user"
  get "orders/show"
  resources :orders, :only => [:index, :show, :destroy]

  resources :sponsors

  get "administration/registrations"
  get "administration/send_mail"
  get "administration/statistics"
  get "administration/caches"
  post "administration/clear_caches"

  # program stuff
  get "program" => "program#index"
  get "program/program"

  #nametags
  get "/nametags" => "nametags#index"
  get "/nametags/:id" => "nametags#show"

  #Info sites
  get "info/about"
  get "info/tema"
  get "info/til_lyntalere"
  get "info/spre_ordet"
  get "info/direkte_mail"
  get "info/sponsor"
  get "info/index"
  get "info/policy"
  get "info/godbiter"
  get "info/gruppepaamelding"
  get "info/sponsor/request"
  get "info/david", to: redirect('/info/keynote')
  get "info/keynote"
  get "info/sosialt"
  get "info/arsmote"
  get "info/smidig_offentlig"
  post "info/sponsor"

  #twitter stuff
  get "twitter/smidig_feed"

  resources :talk_categories

  resources :talk_types

  post '/talks/:id/vote' => 'talks#vote', :as => 'vote'
  post '/talks/:id/status' => 'talks#status', :as => 'status'

  get "talks/list"
  resources :talks

  resources :tickets

  resources :settings

  resources :payment_notifications

  # payment stuff
  get "payments/paypal_completed"
  get "payments/manual_completed"
  get "payments/new_paypal"
  get "payments/new_manual"
  post "payments/create_manual"
  put "payments/update_manual"
  get "payments/complete"
  get "payments/manual"
  get "payments/finish"
  put "payments/invoice_sent"
  resources :payments

  # user stuff
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords" }
  get "users/make_admin"
  match "users/complete/:id" => "users#complete"
  get "users/speaker"
  resources :users
  get "users/delete/:id" => "users#delete"

  resources :tipped_users, :only => :create

  root :to => "my_profile#index"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
  attr_accessible :order_id
  after_create :set_invoice_id
  default_scope order('created_at DESC')
  # Abstract interface for payments, implementations:
  #  - PaypalPayment
  #  - ManualPayment

  #attr_accessible :completed, :completed_at, :manual_company_email, :manual_company_name, :manual_contact_person, :manual_invoice_sent, :manual_post_code, :manual_street_address, :paid_amount, :paypal_currency, :paypal_params, :paypal_payer_email, :paypal_status, :paypal_tx_id, :paypal_tx_type, :price, :order_id

  def set_invoice_id
    time = Time.new.strftime("%Y%m%d")
    if Rails.env == "production"
      self.invoice_id = "#{time}p#{id}"
    else
      self.invoice_id = "#{time}t#{id}"
    end
    save!
  end

  def finish
    transaction do
      self.completed_at = Time.now
      self.completed = true
      order.finish
      save!
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  authorize_admin! :only => [:index, :show, :destroy, :manual, :invoice_sent, :finish, :update_manual]

  authorize_user! :only => [:paypal_completed, :manual_completed, :complete]

  authorize! :only => [:new_paypal, :new_manual, :create_manual] do
    if params[:order_id]
      order = Order.find(params[:order_id])
    elsif params[:manual_payment][:order_id]
      order = Order.find(params[:manual_payment][:order_id])
    end

    unless current_user.admin || order.owner == current_user
      permission_denied('Du er ikke eier av bestillingen')
    end
  end

  before_filter :max_one_payment_per_order, :only => [:new_paypal, :new_manual, :create_manual]
  layout "fullwidth", :only => [:index, :manual]

  def index
    @payments = Payment.all
  end

  def manual
    @incomplete = ManualPayment.all(:conditions => {:manual_invoice_sent => [nil, false]})
    @invoiced = ManualPayment.all(:conditions => {:manual_invoice_sent => true, :completed => [nil, false]})
    @completed = ManualPayment.all(:conditions => {:completed => true})

    respond_to do |format|
      format.html #manual.html.haml
      format.csv  {
        #manual.csv.shaper
        @filename = "Smidig_faktura_#{Date.today.to_formatted_s(:db)}.csv"
      }
    end
  end

  def show
    @payment = Payment.find(params[:id])
    if @payment.type == 'PaypalPayment'
      render "show_paypal"
    else
      render "show_manual"
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  def invoice_sent
    payment = Payment.find(params[:id])
    invoice_id = params[:manual_payment][:manual_invoice_id]

    if invoice_id.blank?
      flash[:alert] = "Du mangler fakturaid for faktura #{payment.id}"
    else
      payment.manual_invoice_sent = true
      payment.manual_invoice_id = invoice_id
      payment.save
    end

    respond_to do |format|
      format.html { redirect_to payments_manual_url }
      format.json { head :no_content }
    end
  end

  def finish
    @payment = Payment.find(params[:id])
    @payment.paid_amount = @payment.price
    @payment.save!
    @payment.finish

    respond_to do |format|
      format.html { redirect_to payments_manual_url }
      format.json { head :no_content }
    end
  end



  def paypal_completed
    # congrat user, open for all!
  end

  def manual_completed
    # congrat user, open for all!
  end

  def new_paypal
    order = Order.find(params[:order_id])
    order.transaction do
      payment = PaypalPayment.new({
          :price => order.price,
          :order_id => order.id
        })
      payment.save!
      redirect_to get_paypal_url(payment)
    end
  end

  def new_manual
    @manual_payment = ManualPayment.new
    @manual_payment.order_id = params[:order_id]
  end

  # Expects manual_order to have order_id set.
  def create_manual
    @manual_payment = ManualPayment.new(params[:manual_payment])
    @manual_payment.price = @manual_payment.order.price

    if @manual_payment.save
      SmidigMailer.manual_payment_created_confirmation(@manual_payment).deliver
      SmidigMailer.manual_payment_created_notification(@manual_payment, payments_manual_url).deliver
      redirect_to :action=> :manual_completed, :id=> @manual_payment.id
    else
      render action: "new_manual"
    end
  end

  # only admis can update!!
  def update_manual
    @payment = ManualPayment.find(params[:id])
    if @payment.update_attributes(params[:manual_payment])
      redirect_to :action=> :index, notice: 'Payment was successfully updated.'
    else
      render "show_manual"
    end

  end

  # Complete an existing payment
  def complete
    payment = Payment.find(params[:id])
    if payment.type == 'PaypalPayment'
      redirect_to get_paypal_url(payment)
    else
      max_one payment.order
    end
  end


  private

  def max_one_payment_per_order
    if params[:order_id]
      order = Order.find(params[:order_id])
    elsif params[:manual_payment][:order_id]
      order = Order.find(params[:manual_payment][:order_id])
    end
    if order.payment && order.payment.type == 'PaypalPayment'
      redirect_to get_paypal_url(order.payment)
    elsif order.payment
      max_one order
    end
  end

  def get_paypal_url(payment)
    payment.payment_url(payment_notifications_url, payments_paypal_completed_url)
  end

  def max_one(order)
    flash[:notice] = 'Kan maks registrere en betaling per bestilling.'
    redirect_to :controller => :orders, :action=> :show, :id => order.id
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def manual_address(payment)
    content_tag(:div) do
      if payment.manual_company_email
        payment.manual_company_email
      else
        concat payment.manual_company_name
        concat tag(:br)
        concat payment.manual_street_address
        concat tag(:br)
        concat payment.manual_post_code
      end
    end
  end

  def participants(payment)
    unless payment.order
      return content_tag(:div, 'WARNING - NO ORDER FOUND', class: 'missing_order')
    end

    content_tag(:div) do
      payment.order.users.each do |user|
        concat user.name
        concat tag(:br)
      end
    end
  end
end

app/views/payments/_manual_group.html.haml
%tr.info
  %td{:colspan => 9}
    %strong &gt; #{title}
- for payment in payments
  %tr
    %td= link_to '#' + payment.id.to_s, {:action => 'show', :id=>payment.id}
    %td= payment.created_at.to_formatted_s(:long)
    %td= "#{payment.price},-"
    %td= "#{payment.paid_amount},-" if payment.paid_amount
    %td= participants(payment)
    %td= payment.manual_contact_person
    %td= manual_address(payment)
    %td= link_to '#'+payment.order.id.to_s, {:controller => :orders, :action => 'show', :id => payment.order.id} if payment.order
    %td.text-right
      - unless payment.manual_invoice_sent
        = simple_form_for payment, :html => {:class => "form-inline"}, :url => "#{payments_invoice_sent_path}" do |f|
          %input{:type => "hidden", :name=>"id", :value => "#{payment.id}"}
          = f.input :manual_invoice_id, :label => false, input_html: { :class => "manual_invoice_id"}
          = f.button :submit, :class => 'btn btn-primary', :value => "Faktura sent"

      - else
        = payment.manual_invoice_id

      - if payment.manual_invoice_sent and not payment.completed
        %br
        = link_to 'Betalt!', {:action => 'finish', :id => payment.id }, :class => 'btn btn-success', :title => "Fullfør betaling"

app/views/payments/_show_common.html.haml
:markdown
  ## Generell info:
  - **ID:** #{@payment.id}
  - **Faktura-ID:** #{@payment.invoice_id}
  - **Ordre-ID:** #{@payment.invoice_id}
  - **Opprettet Dato:** #{@payment.created_at}
  - **Pris:** #{@payment.price}
  - **Innbetalt sum:** #{@payment.paid_amount}
  - **Fullført:** #{@payment.completed ? "Ja" : "Nei"}
  - **Fullført Dato:** #{@payment.completed_at}

app/views/payments/index.html.haml
%a{:href => "#{payments_manual_path}"}
  %i.icon-list
  Følge opp manuelle fakturaer

%h2 Alle betalinger
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Type
      %th Opprettet
      %th Pris
      %th Betalt dato
      %th Betalt sum
      %th Bestilling
      %th
  %tbody
    - for payment in @payments
      %tr
        %td= link_to '#' + payment.id.to_s, {:action => 'show', :id=>payment.id}
        %td= payment.type
        %td= payment.created_at.to_formatted_s(:long)
        %td #{payment.price},-
        %td= payment.completed_at.to_formatted_s(:long) if payment.completed_at
        %td #{payment.paid_amount},-
        %td= link_to '#'+payment.order.id.to_s, {:controller => :orders, :action => 'show', :id => payment.order.id} if payment.order
        %td
          = link_to({:action => 'destroy', :id => payment.id }, :confirm =>"Are you sure", :method=>:delete, :class => 'btn btn-danger', :title => "Slett betaling") do
            %i{:class => "icon-user icon-remove"}

app/views/payments/manual.haml
%a.pull-right{:href => "#{payments_manual_path}.csv"}
  %i.icon-th
  CSV

%a{:href => "#{payments_path}"}
  %i.icon-list
  Alle betalinger




%table{:class => 'table'}
  %thead
    %tr
      %th Id
      %th Opprettet
      %th Pris
      %th Betalt sum
      %th Deltakere
      %th Kontaktperson
      %th Fakturaadresse
      %th Bestilling
      %th.text-right FakturaID
  %tbody
    =render 'manual_group', :payments => @incomplete, :title => "Nye registeringer"
    =render 'manual_group', :payments => @invoiced, :title => "Faktura sent"
    =render 'manual_group', :payments => @completed, :title => "Betalt"

app/views/payments/manual_completed.html.haml
%h2 Takk for din påmelding

%p
  Vi har registrert din henvendelse om å få tilsendt en faktura for din påmelding.
  Vi kommer innen kort tid til å opprette og sende fakturaen i henhold til din
  registrering.

%p
  %a(href="#{my_profile_index_path}") Gå til din påmelding
%br
%br
%br

.fb-like{"data-href" => "http://www.facebook.com/smidig", "data-send" => "true", "data-show-faces" => "true", "data-width" => "300"}

app/views/payments/manual_exists.html.haml
%h2 Fakturaforespørsel
Vi har allerede registrert nødvendig informasjon.

= link_to "Tilbake til bestilling", orders_show_path(:id => @order.id)

app/views/payments/new_manual.html.haml
<h2>Manuell fakturering</h2>

%dl.dl-horizontal
  %dt BestillingsID:
  %dd #{@manual_payment.order.id}
  %dt Påmelder:
  %dd #{@manual_payment.order.owner.name}
  %dt Antall deltakere:
  %dd #{@manual_payment.order.users.count}
  %dt Total pris:
  %dd #{@manual_payment.order.price},-

= simple_form_for @manual_payment, :url => {:action => :create_manual}, :html => { :class => 'form-horizontal'} do |f|
  = f.input :order_id, :as => 'hidden'
  = f.input :manual_contact_person
  = f.input :manual_company_name
  = f.input :manual_organization_number
  = f.input :manual_company_email, :type => "email", :hint => "Dersom du oppgir epost benyttes denne for å sende faktura."

  = f.input :manual_street_address
  = f.input :manual_post_code, :type => "number"
  = f.input :manual_city

  %p
    PS! Dette er en manuell prosess. Det kan ta noen dager før du får tilsendt en faktura!

  .form-actions
    = f.button :submit, :class => 'btn-primary', :value => t("general.manual_payment.create")

app/views/payments/paypal_completed.html.haml
%h2 Takk for din påmelding

%p
  Takk for at du fullførte betalingen hos PayPal. Straks vi mottar en bekreftelse
  på betalingen fra PayPal vil vi sende deg en bekreftelse på epost.

%p
  %a(href="#{my_profile_index_path}") Gå til din påmelding
%br
%br
%br

.fb-like{"data-href" => "http://www.facebook.com/smidig", "data-send" => "true", "data-show-faces" => "true", "data-width" => "300"}

app/views/payments/show_manual.html.haml
=render 'show_common'

%h3 Fakturainfo:

= simple_form_for @payment, :url => {:action => :update_manual, :id => @payment.id}, :html => { :class => 'form-horizontal'} do |f|
  = f.input :manual_contact_person
  = f.input :manual_company_name
  = f.input :manual_organization_number
  = f.input :manual_company_email, :type => "email"
  = f.input :manual_street_address
  = f.input :manual_post_code, :type => "number"
  = f.input :manual_city

  .form-actions
    = f.button :submit, :class => 'btn-primary', :value => t("general.manual_payment.update")

= link_to 'Vis alle betalinger', payments_path

app/views/payments/show_paypal.html.haml
=render 'show_common'

:markdown
  ## Paypal info:
  - **tx_id:** #{@payment.paypal_tx_id}
  - **tx_type:** #{@payment.paypal_tx_type}
  - **currency:** #{@payment.paypal_currency}
  - **status:** #{@payment.paypal_status}
  - **payer_email:** #{@payment.paypal_payer_email}
  - **Alle parameter:** #{@payment.paypal_params}

= link_to 'Vis alle betalinger', payments_path