config/routes.rb
ConferenceApp::Application.routes.draw do

  resources :feedback_votes


  get "roomslots/add_talk"
  get "roomslots/remove_talk"
  resources :talk_comments
  resources :roomslots
  resources :rooms
  resources :timeslots

  resources :workshop_participant

  #MyProfile
  get "my_profile/dinner_registration" => "my_profile#dinner_registration"
  get "my_profile/receipt" => "my_profile#receipt"
  resources :my_profile, :only => "index"

  #order stuff
  get "orders/new_user"
  post "orders/add_user"
  get "orders/show"
  resources :orders, :only => [:index, :show, :destroy]

  resources :sponsors

  get "administration/registrations"
  get "administration/send_mail"
  get "administration/statistics"
  get "administration/caches"
  post "administration/clear_caches"

  # program stuff
  get "program" => "program#index"
  get "program/program"

  #nametags
  get "/nametags" => "nametags#index"
  get "/nametags/:id" => "nametags#show"

  #Info sites
  get "info/about"
  get "info/tema"
  get "info/til_lyntalere"
  get "info/spre_ordet"
  get "info/direkte_mail"
  get "info/sponsor"
  get "info/index"
  get "info/policy"
  get "info/godbiter"
  get "info/gruppepaamelding"
  get "info/sponsor/request"
  get "info/david", to: redirect('/info/keynote')
  get "info/keynote"
  get "info/sosialt"
  get "info/arsmote"
  get "info/smidig_offentlig"
  post "info/sponsor"

  #twitter stuff
  get "twitter/smidig_feed"

  resources :talk_categories

  resources :talk_types

  post '/talks/:id/vote' => 'talks#vote', :as => 'vote'
  post '/talks/:id/status' => 'talks#status', :as => 'status'

  get "talks/list"
  resources :talks

  resources :tickets

  resources :settings

  resources :payment_notifications

  # payment stuff
  get "payments/paypal_completed"
  get "payments/manual_completed"
  get "payments/new_paypal"
  get "payments/new_manual"
  post "payments/create_manual"
  put "payments/update_manual"
  get "payments/complete"
  get "payments/manual"
  get "payments/finish"
  put "payments/invoice_sent"
  resources :payments

  # user stuff
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords" }
  get "users/make_admin"
  match "users/complete/:id" => "users#complete"
  get "users/speaker"
  resources :users
  get "users/delete/:id" => "users#delete"

  resources :tipped_users, :only => :create

  root :to => "my_profile#index"
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  attr_accessible :end, :start, :is_workshop_slot
  has_many :roomslot
  default_scope order('timeslots.start ASC, timeslots.end ASC')

  def description
    "#{self.start} - #{self.end} - #{self.is_workshop_slot? ? 'Workshop' : 'Not Workshop'}"
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  authorize_admin!
  layout "fullwidth"
  
  # GET /timeslots
  # GET /timeslots.json
  def index
    @available_talks = Talk.where(:roomslot_id => nil).where(:status => 'approved_and_confirmed')
    
    @timeslots = Timeslot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timeslots }
    end
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timeslot }
    end
  end

  # GET /timeslots/new
  # GET /timeslots/new.json
  def new
    @timeslot = Timeslot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeslot }
    end
  end

  # GET /timeslots/1/edit
  def edit
    @timeslot = Timeslot.find(params[:id])
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(params[:timeslot])

    respond_to do |format|
      if @timeslot.save
        flash[:notice] = 'Timeslot was successfully created.'
        format.html { redirect_to :action => :index }
        format.json { render json: @timeslot, status: :created, location: @timeslot }
      else
        format.html { render action: "new" }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timeslots/1
  # PUT /timeslots/1.json
  def update
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      if @timeslot.update_attributes(params[:timeslot])
        flash[:notice] = 'Timeslot was successfully updated.'
        format.html { redirect_to :action => :index }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeslot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy

    respond_to do |format|
      format.html { redirect_to timeslots_url }
      format.json { head :no_content }
    end
  end
end

app/views/timeslots/_form.html.haml
= simple_form_for target, :html => { :class => 'form-horizontal' } do |f|
  = f.input :start
  = f.input :end
  = f.input :is_workshop_slot

  = render 'shared/formactions', :f => f

app/views/timeslots/_talk.html.haml
%li.talk{:draggable => 'true', :title => 'Dra meg til et rom', :data => {:talk_id=>talk.id}}
  #{talk.id}: #{talk.title}
  %em #{talk.user.name}
  (#{talk.talk_type.name}, #{talk.talk_category.name})
  %a.remove{:href=>'delete_talk'}
    %i.icon-remove

app/views/timeslots/_timeslot.html.haml
.timeslot
  %header
    #{timeslot.start.to_formatted_s(:long)} - #{timeslot.end.to_formatted_s(:long)}
    %span.pull-right
      %a{:href=>"#{new_roomslot_path}?timeslot_id=#{timeslot.id}", :title => "Legg til rom"}
        %i{:class => "icon-plus"}
      = link_to(edit_timeslot_path(timeslot), :title => "Editer timeslot") do
        %i{:class => "icon-edit"}
      = link_to(timeslot, :method => :delete, :data => { :confirm => 'Are you sure?' }) do 
        %i{:class => "icon-remove"}

  .rooms
    - timeslot.roomslot.each do |roomslot|
      .room
        %span.pull-right
          &nbsp;
          = link_to(edit_roomslot_path(roomslot), :title => "Slett rom") do
            %i{:class => "icon-edit"}
          = link_to(roomslot, :method => :delete, :data => { :confirm => 'Are you sure?' }) do 
            %i{:class => "icon-remove"}
        %strong Room: 
        #{roomslot.room.name}
        - if roomslot.title 
          %br
          %strong Tittel: 
          #{roomslot.title}

        .talks
          %strong Foredrag:
          %ul.dropzone{:data => {:roomslot_id => "#{roomslot.id}"}}
            - roomslot.talks.each do |talk|
              = render 'talk', :talk => talk

    .clear

app/views/timeslots/edit.html.haml
= render 'shared/title', :prefix => 'Edit'

= render 'form', :target => @timeslot
= render 'shared/buttonrow', :target => @timeslot

app/views/timeslots/index.html.haml
.program-admin
  .span9
    %h1 Tidsslotter:
    - @timeslots.each do |timeslot|
      = render 'timeslot', :timeslot => timeslot

    %p
      = link_to new_timeslot_path, :class => 'btn btn-default' do
        %i.icon-plus
        Legg til timeslot

  .span3
    .available-talks-container
      %h4 Godkjente talks:
      %ul.available-talks.talks
        - for talk in @available_talks
          = render 'talk', :talk => talk

app/views/timeslots/new.html.haml
= render 'shared/title', :prefix => 'Edit'

= render 'form', :target => @timeslot
= render 'shared/buttonrow'

app/views/timeslots/show.html.haml
= render 'shared/title', :prefix => 'Show'

%p#notice= notice

%p
  %b Start:
  = @timeslot.start
%p
  %b End:
  = @timeslot.end

= render 'shared/buttonrow', :target => @ticket