config/routes.rb
ConferenceApp::Application.routes.draw do

  resources :feedback_votes


  get "roomslots/add_talk"
  get "roomslots/remove_talk"
  resources :talk_comments
  resources :roomslots
  resources :rooms
  resources :timeslots

  resources :workshop_participant

  #MyProfile
  get "my_profile/dinner_registration" => "my_profile#dinner_registration"
  get "my_profile/receipt" => "my_profile#receipt"
  resources :my_profile, :only => "index"

  #order stuff
  get "orders/new_user"
  post "orders/add_user"
  get "orders/show"
  resources :orders, :only => [:index, :show, :destroy]

  resources :sponsors

  get "administration/registrations"
  get "administration/send_mail"
  get "administration/statistics"
  get "administration/caches"
  post "administration/clear_caches"

  # program stuff
  get "program" => "program#index"
  get "program/program"

  #nametags
  get "/nametags" => "nametags#index"
  get "/nametags/:id" => "nametags#show"

  #Info sites
  get "info/about"
  get "info/tema"
  get "info/til_lyntalere"
  get "info/spre_ordet"
  get "info/direkte_mail"
  get "info/sponsor"
  get "info/index"
  get "info/policy"
  get "info/godbiter"
  get "info/gruppepaamelding"
  get "info/sponsor/request"
  get "info/david", to: redirect('/info/keynote')
  get "info/keynote"
  get "info/sosialt"
  get "info/arsmote"
  get "info/smidig_offentlig"
  post "info/sponsor"

  #twitter stuff
  get "twitter/smidig_feed"

  resources :talk_categories

  resources :talk_types

  post '/talks/:id/vote' => 'talks#vote', :as => 'vote'
  post '/talks/:id/status' => 'talks#status', :as => 'status'

  get "talks/list"
  resources :talks

  resources :tickets

  resources :settings

  resources :payment_notifications

  # payment stuff
  get "payments/paypal_completed"
  get "payments/manual_completed"
  get "payments/new_paypal"
  get "payments/new_manual"
  post "payments/create_manual"
  put "payments/update_manual"
  get "payments/complete"
  get "payments/manual"
  get "payments/finish"
  put "payments/invoice_sent"
  resources :payments

  # user stuff
  devise_for :users, :controllers => { :registrations => "registrations",
                                       :sessions => "sessions",
                                       :passwords => "passwords" }
  get "users/make_admin"
  match "users/complete/:id" => "users#complete"
  get "users/speaker"
  resources :users
  get "users/delete/:id" => "users#delete"

  resources :tipped_users, :only => :create

  root :to => "my_profile#index"
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  no_authorization!
end

app/views/info/about.html.haml
= render "menu"

%h1 Smidig 2016
.row-fluid
  .span7
    :markdown
      Årets konferanse er den tiende i rekken og finner sted 24. - 25. oktober.

      [Meld deg på årets konferanse](/users/sign_up)

      ## Om Smidigkonferansen
      
      Vi tror at IT-prosjekter i Norge kan lære mye av prinsippene bak smidig utvikling. Derfor arrangerer vi
      Smidigkonferansen for å dele erfaringer og bidra til å øke kunnskapen om smidige metoder i Oslo og Norge.

      Smidigkonferansen er en årlig konferanse for og av fagmiljøet selv. Her får du høre hvordan andre
      prosjektdeltakere som deg takler hverdagen i sine smidige og kanskje ikke så smidige prosjekter. Her får du
      stiftet nye bekjentskaper som er i samme situasjon som deg selv. Du får forsterket de bekjentskapene du har, og
      lært hvor mye både fagmiljøet og du selv har å by på. I fjor var ca 20% av deltakerne også foredragsholdere, noe
      som skaper en unik atmosfære. Ikke bare får du høre interessante foredrag, men det er lett å snakke med
      foredragsholderne gjennom hele konferansen.

      ## Vårt unike format

      Begge konferansedagene følger samme format: Lyntaler (korte, erfaringsbaserte foredrag) før lunsj og
      diskusjonsgrupper (open space) etter lunsj. Hver lyntale er på ti minutter, så i løpet av formiddagen vil du få
      med deg intill 12 forskjellige lyntaler. I Open Space etter lunsj stemmer deltakerne selv frem hvilke temaer de
      ønsker å fordype seg i, og jobber så med disse problemstillingene i mindre grupper. Enkle regler sikrer
      interaktivitet og faglig utbytte for deltakerne.

      ### Keynote
      Også i år skal vi hente spennende foredragsholdere som inviteres til å holde keynotes på Smidig 2016.

      ### Lyntaler
      Lyntaler (”lightning talks” på engelsk) er tapas i foredragsholdernes verden: man får mange impulser fra mange
      forskjellige folk. På Smidig er tidsbegrensning til lyntaler ti minutter. Dette inspirerer foredragsholderne til å
      destillere budskapet sitt ned til det aller viktigste, og fjerne alle unødvendige deler. Har du noe på hjertet?

      ### Workshops

      Også i år kommer vi til å kjøre flere spennende workshops under konferansen. Dette er en unik mulighet for
      deltakerne til å lære noe noe nytt.

      ### Open space
      I Open space, en type diskusjonsgruppe, dykker man dypere ned i de temaene deltakerne selv synes er mest
      interessante. Legenden sier at ideen til Open Space ble født av observasjonen om at på tradisjonelle konferanser
      er det ofte diskusjonene i kaffepausen som er mest givende. Tanken er å sette rammer som gjenskaper denne
      stemningen hvor man deler erfaringer og lærer av hverandre. Med inspirasjon fra lyntalene, eller med fokus på
      akkurat det problemet du sliter med i din organisasjon, har du en unik mulighet til å diskutere temaet nærmere med
      andre som har tilsvarende interesser og problemstillinger.

  .span5
    .image
      =image_tag (image_path "smidig2012_4.jpg")
      %p.caption
        Keynote fra Smidig 2012 
    .image
      =image_tag (image_path "smidig2012_1.jpg")
      %p.caption
        Open Space tavlen i 2012
    .image
      =image_tag (image_path "smidig2012_5.jpg")
      %p.caption
        Engasjerte deltakere

app/views/info/david.html.haml
= render "menu"

%h1 Keynote
.row-fluid
  .span7
    :markdown

      *Også i år vil vi ha to keynote-holdere på Smidigkonferansen. Begge dagene vil starte med en keynote og vi håper disse vil bidra til å gi folk en inspirerende start på dagen.* 
      ## David Anderson

      David Anderson er et velkjent navn i smidig-verdenen. Han introduserte Kanban for programvareutvikling og har siden da etablert seg som en av de mest toneangivende personene i det han selv kaller «den 2. generasjonen av smidig utvikling». Han er direktør i Lean-Kanban University og forfatter av en rekke essensielle bøker som: *Agile Management for Software Engineering: Applying the Theory of Constraints for Business Results* og *Kanban: Successful Evolutionary Change for Your Technology Business*. Han er en prominent foredragsholder og vi er stolte av å ha fått David til å holde keynote på Smidig 2013. 

      InfoQ skrev tidligere i år følgende om David Anderson: 

    %blockquote
      :markdown
        If they were to carve a new Mt. Rushmore into the mountains surrounding Silicon Valley, then alongside Dijkstra, Kernighan, The Three Amigos and The Gang of Four they would need to make room for David J. Anderson, father of Kanban in the software development industry.

  .span5
    .image
      =image_tag (image_path "david.jpg")
      %p.caption
        David J. Anderson
    .image
      =image_tag (image_path "smidig2012_4.jpg")
      %p.caption
        Keynote fra Smidig 2012 
  

app/views/info/direkte_mail.html.haml
= render "menu"
%h2.page_title Direkte mail
#mail
  %p Hei!
  %p
    Fagmiljøet rundt smidige metoder i Oslo er blant verdens mest aktive.
    Vi har flere scrummastere per innbygger og flere smidige prosjekter
    per innbygger enn noe annet sted i verden. Dette gjør sitt til at det
    er utrolig mange mennesker i byen som har erfaringer med smidige metoder
    og som har noe å dele med andre. For tiende gang inviterer entusiaster i fagmiljøet
    til Smidig-konferansen som avholdes 24. - 25. oktober i Oslo.
  %p
    Smidig-konferansen er en konferanse for og av fagmiljøet selv.
    Her får du høre hvordan andre prosjektdeltakere som deg takler hverdagen
    i sine smidige og kanskje ikke så smidige prosjekter. Her får du stiftet
    nye bekjentskaper som er i samme situasjon som deg selv. Du får forsterket
    de bekjentskapene du har, og lært hvor mye både fagmiljøet og du selv har å
    by på. I fjor var over 20% av deltakerne også foredragsholdere, noe som
    skaper en unik atmosfære. Ikke bare får du høre interessante foredrag, men
    det er lett å snakke med foredragsholderne gjennom hele konferansen.
  %p
    Vi har åpnet for påmelding både for deltakere og foredragsholdere.
    Det er allerede kommet inn mange spennende forslag til programmet.
    Les mer på nettsidene og
    
    %a{:href => "http://twitter.com/smidig"} følg @smidig på Twitter
    
    Sitter du inne med en idé, frustrasjon, erfaring
    eller noe annet du vil fortelle, meld inn ditt eget forslag!
  %p
    Gå til
    %a{:href => "http://smidig.no"} http://smidig.no
    og meld deg på i dag.
  %p
    Med vennlig hilsen
    %br/
    Entusiastene bak Smidig 2016
  %p
    PS: Konferansen er avhengig av hjelp fra deltagerne til markedsføring.
    Vi setter stor pris på om du videresender denne mailen til dine kolleger.

app/views/info/gruppepaamelding.html.haml
.row-fluid
  .span6
    %h2 Gruppepåmelding

    %p 
      Gruppepåmelding gjør at du kan melde på hele avdelingen og be om å få tilsendt 
      en faktura. 

    %h3 Hvordan virker det?
    :markdown
      1. Meld deg på som deltaker til smidig 2016.
      2. Velg «Legg til deltaker». (bilde 1)
      3. Fyll ut kollegas navn, epost og tlf. (bilde 2)
      3. Velg «Be om faktura»  (bilde 3)
      4. Fyll ut faktura-detaljer.
      5. Vi sender en faktura direkte til ditt firma.

      [Meld deg på Smidig nå!](#{new_user_registration_path})

  .span6
    %p 
      =image_tag (image_path "gruppepamelding_steg1.png")
      %h6 Bilde 1

      =image_tag (image_path "gruppepamelding_steg2.png")
      %h6 Bilde 2   

      =image_tag (image_path "gruppepamelding_steg3.png")
      %h6 Bilde 3

app/views/info/index.html.haml
-#
  .row-fluid.news
    .span6
      %article
        :markdown
          ##[Inviterte foredragsholdere på Smidig 2016](#{info_keynote_path})

          Vi er stolte av å kunne annonsere følgende inviterte foredragsholdere:
          
          * Frode Ødegård (Post-Lean and Higher-Order Organizations: Building the Future)
          * Gitte Klitgaard (Do you have the courage to be agile?)
          * Torgeir Dingsøyr & Nils Brede Moe (Studier av store, distribuerte og smidige prosjekter)
          * Johannes Brodwall (Ikke tjuvstart uten oss utviklere)
          * Christin Gorman ("Bruk og kast" utvikling gir bedre programmer)
          * Sven Schnee (#NoEstimates, the art of getting your product development back on track)
          * Jon Kåre Stene (David og Goliat - organisasjonsformer i fremtiden)

        %a(href="#{info_keynote_path}")
          Les mer om inviterte foredragsholdere

    .span6
      %article
        :markdown
          ##[Gruppepåmelding](#{info_gruppepaamelding_path})

          Også i år tilbyr Smidigkonferansen gruppepåmelding. Dette forenkler påmelding og betaling for
          bedrifter som ønsker å sende flere deltakere

        %a.pull-right(href="#{info_gruppepaamelding_path}")
          Les mer om gruppepåmelding

  .row-fluid.news
    .span6
      %article

        :markdown
          ##[Sponse Smidig 2016?](#{info_sponsor_path})

          Konferansen finansieres av deltakeravgift og sponsormidler.
          Å være sponsor for Smidig 2016 er et sterkt signal om at selskapet stiller seg
          bak bevegelsen for smidige metoder og støtter opp under det frivillige initiativet som er
          drivkraften bak arrangement.

        %a(href="#{info_sponsor_path}")
          Les mer om å sponse årets Smidigkonferanse

    .span6
      %article
        :markdown
          ##[Det beste fra Smidigkonferansen](https://vimeo.com/album/3107510)

          Trenger du inspirasjon? Alle foredragene fra tidligere konferanser finner du på Vimeo

        %a.pull-right(href="https://vimeo.com/album/3107510")
          Se fjorårets foredrag

  .row-fluid.news
    .span6
      %article
        :markdown
          ##[Om konferansen](#{info_about_path})

          Smidigkonferansen er en årlig konferanse for og av fagmiljøet selv. Her får du høre hvordan andre
          prosjektdeltakere som deg takler hverdagen i sine smidige og kanskje ikke så smidige prosjekter.

        %a(href="#{info_about_path}")
          Les mer om Smidigkonferansen

app/views/info/keynote.html.haml
= render "menu"
-#
  %h1 TBA


%h1 Keynote på Smidig 2016
.row-fluid
  .span7
    :markdown


      ## Frode Ødegård
      Frode immigrated to Silicon Valley from Norway 25 years ago, has started several companies and for the last 10+ years has run the Lean Systems Institute (LSI). From 2004-2014 LSI worked to reinvent Lean for knowledge work, working with senior leaders in client firms here (from small companies up to Lockheed and Honeywell) as well as in Scandinavia


      **Tema: “Post Lean and Higher Order Organizations: Building the Future”**

      >In the last year, LSI’s focus has been on how mature companies must innovate at the speed of startups – or even faster. They call this Post-Lean, because a lot of basic assumptions behind Lean are being invalidated. Post-Lean is about what happens to innovation and organizational design when technologies are developing exponentially.




      ## Johannes Brodwall
      En svært tverrfaglig utvikler, arkitekt, konsulent, ledertype og ikke minst smidigpådriver.
      Johannes er velkjent for de fleste i norsk utvikler-miljø. Han har i en årrekke vært pådriver og arrangør for en mengde smidig-initiativ som blant annet Smidigkonferansen og Oslo XP-meetup. Johannes tilhører de få som har tung og bred teknisk kompetanse, samtidig som han forstår seg på tilgrensende fagfelt som ledelse, drift og metodikk. 

      **Tema: "Ikke tjuvstart uten oss utviklere"**

      >Hva er egentlig riktig mengde forarbeid før utviklere skal sette i gang med et prosjekt? I de fleste prosjekter opplever man som utvikler at det er gjort mange antagelser og forutsetninger om spørsmål som egentlig ikke var viktige, men som har blitt det. Samtidig er de spørsmålene som vil være avgjørende for å kunne gi en god teknisk løsning har blitt oversett eller besvart på sviktende grunnlag.

      >Johannes argumenterer for at  det er mange aktiviteter man ikke bør starte med før man har sjansen til å sette tennene i den tekniske delen av et prosjekt. Hvilke spørsmål må besvares før man starter og i hvilke spørsmål må man ikke tjuvstarte uten utviklere?



      ## Christin Gorman
      Christin er utvikler og ettertraktet foredragsholder med helikoptersyn, sterke meninger og stort engasjement. Hun har for tiden eget firma, Not a Number, men har deltatt på en rekke utviklingsprosjekter i både offentlig og privat sektor.

      **Tema: "'Bruk og kast' utvikling gir bedre produkter"**

      >Scrum har fått oss alle til å jobbe i inkrementer.  Hver 3. uke eller deromkring lager vi en “release” som er “potentially shippable”. Med vekt på “potentially”. For vi gidder ikke faktisk levere den til noen.  Det hadde jo blitt så mye jobb.  Så har vi en retrospektiv der vi internt i teamet snakker om prosessen vår og hvordan den kan forbedres.  Så kaller vi oss smidige. Vår interne prosess blir kontinuerlig endret og forbedret, men hva med produktet? Blir det endret og forbedret underveis?




      ## Sven Schnee
      Scrum Master and Agile Coach with developer background working with Continuous Improvement at Holidaycheck. Sven i dedicated to agile and Lean because he has experienced how these approaches are so much better at helping companies to deliver products that matter, and make their customers happier.

      **Tema: "#NoEstimates, the art of getting your product development back on track"**

      >First: why we are doing estimates, what questions we try to answer with it and the reasoning behind.
      >Then, how can you use #NoEstimates theoretically for your Product Development. And by that get the answers that you are seeking without the added effort that estimates bring.
      >Since theories are boring but practical examples are much more compelling the session will end by practical examples and different tools and methods that you can use to master #NoEstimates.


      ## Gitte Klitgaard
      Experienced agile coach, pirate and dragon lady. Gitte has worked within software development for more than ten years. Since 2010 she worked as an agile coach with rollout of agile in large organizations, and coaching, trainings, workshops, process development and much more.
      Latest interest is courage and vulnerability at work, which she also talks about at conferences.

      **Tema: "Do you have the courage to be agile?"**

      >Agile is actually really simple and yet it can be hard to do. Not only the processes, the mindset is even harder.
      I believe that one of the core elements of being agile is having courage. Without courage you do not really get anywhere. But what is courage? And do you have the courage to go all in?


      ## Torgeir Dingsøyr og Nils Brede Moe
      Forskere fra Sintef med lang erfaring fra studier av programvareorganisasjoner.
      Nils Brede Moe forsker på hvordan smidige metoder benyttes i små og store prosjekter, hvordan distribuerte team bruker smidige metoder både innenfor land og mellom land, og hvordan Lean Startup kan kombineres med smidig.

      Torgeir Dingsøyr forsker på prosessforbedring og kunnskapsforvaltning i programvarebedrifter som sjefsforsker i SINTEF. Spesielt har han fokusert på smidige utviklingsmetoder, teamarbeid i systemutvikling og bruk av intranettverktøy for læring mellom prosjekter. Han leder forskningsprosjektet Agile 2.0 hvor Kantega, Kongsberg Gruppen, Sopra Steria, Sticos og NTNU er partnere.

      **Tema: "Smidig utenfor komfortsonen: I store og i distribuerte prosjekter"**

      >Smidige metoder var beregnet på små, samlokaliserte team som skulle lage programvare som ikke er sikkerhetskritisk. Suksessen med metodene for små team har ført til at mange har brukt metodene også utenfor komfortsonen: I store prosjekter og i distribuerte team. Vi ser på hva som er utfordringer med smidige metoder i disse feltene, oppsummerer hva vi kan lære av studier, og spekulerer i hva vi tror vil kreves i smidige metoder fremover.

      ## Jon Kåre Stene
      Jon Kåre Stene har i mange år jobbet med LEAN i alle slags miljøer og de siste årene spesielt innen innovasjon. Med bakrgrunn fra Schibsted, consulting og gründervirksomhet har nysjerrigheten  rundt hva som skaper grobunn for utvikling og forbedring alltid vært stor.

      **Tema: "David og Goliat - hvilke organisasjonsformer som kommer til å vinne i fremtiden"**

      >Foredraget setter fokus på noen egenskaper dagens og fremtidens skusesselskaper innehar og som gamle, etablerte «Goliather» sliter med å adoptere. Hva skal til for å skape den nødvendige farten i en verden i stadig raskere utvikling? For mange vil dette være snakk om være eller ikke være!

  .span5
    .image
      =image_tag (image_path "persons/frode_odegaard.png")
      %p.caption
        Frode ødegård
    .image
      =image_tag (image_path "persons/johannes_brodwall.png")
      %p.caption
        Johannes Brodwall
    .image
      =image_tag (image_path "persons/christin_gorman.png")
      %p.caption
        Christin Gorman
    .image
      =image_tag (image_path "persons/sven_schnee.png")
      %p.caption
        Sven Schnee
    .image
      =image_tag (image_path "persons/gitte_klitgaard.png")
      %p.caption
        Gitte Klitgaard
    .image
      =image_tag (image_path "persons/torgeir_nils.png")
      %p.caption
        Torgeir Dingsøyr og Nils Brede Moe
    .image
      =image_tag (image_path "persons/jon_kaare_stene.jpg")
      %p.caption
        Jon Kåre Stene

app/views/info/policy.html.haml
.row-fluid
  .span12
    :markdown
      # Sikkerhet og personvern

      Smidigkonferansen kommer aldri til å selge videre dine personopplysninger til en tredjepart eller levere ut opplysninger til utenforstående. Vi benytter dem kun for å håndtere din påmelding til konferansen og sende deg mail i henhold til valgene du gjør ved registrering. Ved registrering samtykker du i at de oppgitte opplysninger lagres.

      Dersom du godtar å motta e-post fra konferansen vil kunne melde deg av listen med en link i mailen.

      Du må være over 18 år for å melde deg på Smidigkonferansen.

      For øvrig vises til gjeldende norske lover og regler.

      [Meld deg på konferansen!](#{new_user_registration_path})

app/views/info/tema.html.haml
= render "menu"

%h1 Tema på Smidig 2016
.row-fluid
  .span10
    :markdown
      Som alltid er vi interessert i reelle erfaringer fra smidig  utvikling innen IT-bransjen.

      [Lever ditt forslag i nå!](#{new_talk_path})

      Spesielt i år ønsker programkomiteen å trekke frem følgende temaer: Smidig programmering, Lean startup, Storskala Smidig, Smidig kultur, Hyppige Leveranser, Gevinst, Endring, Distribuerte Teams og #NoEstimates
      Under finner du en kort beskrivelse av hvert tema og noen stikkord. Har du erfaringer innenfor disse temaene?

      **I så fall burde du [sende inn ditt forslag](#{new_talk_path})** 


      *Siste frist for å levere ditt forslag er #{l talk_suggestion_deadline, :format => '%-d. %B'}.*

      ### Smidig programmering

      ### Lean startup

      ### Storskala Smidig

      ### Smidig kultur

      ### Hyppige Leveranser

      ### Gevinst

      ### Endring

      ### Distribuerte Teams

      ### #NoEstimates


      <!--
      ### Smidig og offshoring

      Offshoring har blitt mer og mer vanlig de siste årene. Hvordan gjennomfører man utvikling med distribuerte team på
      en best mulig måte? [Les mer på Wikipedia](http://en.wikipedia.org/wiki/Information_technology_outsourcing).

      **Noen stikkord:**

      * Kommunikasjon
      * Spesifikasjoner
      * Dokumentasjon
      * Team-sammensetning
      * Kvalitetssikring
      * Kulturforskjeller

      ### Smidig risikostyring

      Hvordan kan man i smidig systemutvikling holde styring og senke risiko for forsinkelser, overruns og skape
      trygghet på status for beslutningstagere?

      **Noen stikkord:**

      * Balansering av risiko
      * Risiko og hyppige leveranser
      * Kontrollrutiner
      * Bruk av omfang som styringsparameter
      * Kontraksformer
      * (Gjennomføring)
      * (Informasjonskvalitet)

      ### Verdiskapning

      Formålet med all systemutvikling er å skape verdi på en eller annen måte. Men hva er verdi og hvordan kan man
      maksimere den?

      **Noen stikkord:**

      * Hva er verdi?
      * Hvordan måles verdi?
      * Kan man benytte verdi som en enhet til og prioritere oppgaver?
      * Hvilke verktøy kan benyttes?
      * Hvem vurderer hva som er av verdi?
      * Hvordan verifiserer man verdi levert?

      ### Erfaringsrapporter

      Vi snakker mye om smidig og hvordan man teoretisk skal bruke smidige teknikker for å få et best mulig resultat.
      Men hvordan fungerer dette i praksis? Vi ønsker å utfordre våre foredragsholdere både til å snakke om det som har
      gått bra og det som har feilet miserabelt i smidig utvikling!

      **Noen stikkord:**

      * Hva var planen?
      * Hva fungerte? Hvorfor?
      * Hva fungerte ikke? Hvorfor?
      * Anbefalinger til andre?

      ### DevOps

      Koble utviklere med de som drifter applikasjonen, slik at bedriften har en løsning som kan endre seg ofte samtidig
      som den er stabil.

      **Noen stikkord:**

      * Utvikling vs drift
      * Kontinuerlige leveranser
      * Operators
      * Stabilitet
      * Smertefri utrulling
      * Puppet

      ### Systemtenkning

      Systemtenkning er prosessen med å forstå hvordan ting, sett på som systemer, påvirker hverandre hverandre som en
      helhet. I et team vil alle teammedlemmer påvirke hverandre og det finnes et uendelig sett med utfall. Hvordan kan
      vi påvirke dette? [Les mer på Wikipedia](http://en.wikipedia.org/wiki/Systems_thinking).

      **Noen stikkord:**

      * Ledelse av team
      * Selvorganiserende team
      * Bruk av Incentiver
      * Bevissthet rundt kompleksitet
      * Teknikker for samarbeid
      * Verktøy

      ### Lean

      Lean filosofi har vært et kjent begrep i mange år, men ser ut til å ha blitt mer og mer sentralt for mange
      selskaper de siste årene. Hvor langt har vi kommet? Hvordan kan lean hjelpe oss for å oppnå bedre resultater? [Les
      mer på Wikipedia](http://en.wikipedia.org/wiki/Lean_manufacturing).

      **Noen stikkord:**

      * Hvordan implementere et lean tankesett i en organisasjon?
      * (Hvordan sette mål for lean?)
      * (Hvordan måle suksess?)
      * Ende-til-ende optimlisering
      * Pull-prinsippet
      * Eksempler på “Waste” i kunnskapsarbeid
      * Flyteffektivitet vs. Ressurseffektivitet
      * Teknikker
      * Verktøy

      ### Kontinuerlig forbedring

      Både innenfor Lean og i smidige systemutvikling ønsker man kontinuerlig forbedring. Men hvar er egentlig dette og
      hvordan måler man det? Er det nok å ha retrospektives for å styre prosesser i en bedre retning?

      **Noen stikkord:**

      * Retrospective
      * Leveransehyppighet og læring
      * Kvalitetsparametere
      * Forbedring, men forbedring for hvem?
      * Teknikker
      * Verktøy

      ### Software craftsmanship

      Med inspirasjon fra «[Manifesto for Software Craftsmanship](http://manifesto.softwarecraftsmanship.org/)» ønsker
      vi å løfte fokuset på håndverket bak programvareutviklking.

      **Noen stikkord:**

      * Ikke-funksjonelle krav
      * Innføring av par-programmering
      * Verktøy for å måle teknisk gjeld
      * Deployment
      * Hurtig feedback
      * Git arbeidsflyter
       * feature branch vs. feature toggle osv
      * Testing
      * Vertøy for testing
      * Kontinuerlig testing
      * Mutation testing
      * Definisjon av ferdig (DoD)

      
      ### [Lever ditt forslag nå!](#{new_talk_path})
      -->

%h1 Nivåer for foredrag
.row-fluid
  .span10
    :markdown
      I år har vi også valgt å innføre nivå på lyntalene som skal holdes. Ved forslag til lyntaler ønsker vi derfor at
      dere selv anbefaler nivå slik at andre kan ha en forventning om hva som kreves av forkunnskaper før de kommer.

      **Ny og nysgjerrig**  
      Svært få eller ingen forkunnskaper om smidig er nødvendig. Overkommelig med sunn fornuft!

      **Husvarm**  
      Deltagere antas å ha testet ut smidig eller lest om det på forhånd. 

      **Vært ute en vinternatt før**  
      Foredrag på dette nivået bygger videre på allerede eksisterende teori, og det er en nødvendighet at deltagere har
      opplevd smidig systemutvikling i praksis, og kjenner til mye teori på området.